spring.application.name=portugese-for-kids-backend
spring.autoconfigure.exclude=org.springframework.ai.model.vertexai.autoconfigure.embedding.VertexAiEmbeddingConnectionAutoConfiguration,org.springframework.ai.model.vertexai.autoconfigure.embedding.VertexAiTextEmbeddingAutoConfiguration,org.springframework.ai.model.vertexai.autoconfigure.embedding.VertexAiMultiModalEmbeddingAutoConfiguration
server.address=${SERVER_ADDRESS:127.0.0.1}
server.port=${PORT:8081}
spring.ai.vertex.ai.gemini.project-id=${GOOGLE_CLOUD_PROJECT}
spring.ai.vertex.ai.gemini.location=${GOOGLE_CLOUD_LOCATION:us-central1}
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-lite
spring.ai.vertex.ai.gemini.chat.options.temperature=0.4
spring.ai.vertex.ai.gemini.chat.options.top-k=40
spring.ai.vertex.ai.gemini.chat.options.top-p=0.85
spring.ai.vertex.ai.gemini.chat.options.frequency-penalty=0.3
spring.ai.vertex.ai.gemini.transport=grpc
hf.api.token=${HF_API_TOKEN:}
