spring.application.name=portugese-for-kids-backend
server.address=127.0.0.1
server.port=8081
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.base-url=https://api.openai.com
