spring.application.name=portugese-for-kids-backend
server.address=127.0.0.1
server.port=8081
spring.ai.vertex.ai.gemini.project-id=${GOOGLE_CLOUD_PROJECT}
spring.ai.vertex.ai.gemini.location=${GOOGLE_CLOUD_LOCATION:us-central1}
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-lite
spring.ai.vertex.ai.gemini.transport=grpc
